/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainLayoutRouteRouteImport } from './routes/(main-layout)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainLayoutAboutUsRouteImport } from './routes/(main-layout)/about-us'
import { Route as mainLayoutVegetablesRouteRouteImport } from './routes/(main-layout)/vegetables/route'
import { Route as mainLayoutVegetablesIndexRouteImport } from './routes/(main-layout)/vegetables/index'
import { Route as mainLayoutFruitsIndexRouteImport } from './routes/(main-layout)/fruits/index'
import { Route as mainLayoutVegetablesTomatoeRouteImport } from './routes/(main-layout)/vegetables/tomatoe'
import { Route as mainLayoutVegetablesPepperRouteImport } from './routes/(main-layout)/vegetables/pepper'
import { Route as mainLayoutVegetablesCucumberRouteImport } from './routes/(main-layout)/vegetables/cucumber'
import { Route as mainLayoutvaluesVisionMissionRouteImport } from './routes/(main-layout)/(values)/vision-mission'
import { Route as mainLayoutvaluesSustainabillityRouteImport } from './routes/(main-layout)/(values)/sustainabillity'
import { Route as mainLayoutvaluesQualityPolicyRouteImport } from './routes/(main-layout)/(values)/quality-policy'

const mainLayoutRouteRoute = mainLayoutRouteRouteImport.update({
  id: '/(main-layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutAboutUsRoute = mainLayoutAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => mainLayoutRouteRoute,
} as any)
const mainLayoutVegetablesRouteRoute =
  mainLayoutVegetablesRouteRouteImport.update({
    id: '/vegetables',
    path: '/vegetables',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutVegetablesIndexRoute =
  mainLayoutVegetablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutFruitsIndexRoute = mainLayoutFruitsIndexRouteImport.update({
  id: '/fruits/',
  path: '/fruits/',
  getParentRoute: () => mainLayoutRouteRoute,
} as any)
const mainLayoutVegetablesTomatoeRoute =
  mainLayoutVegetablesTomatoeRouteImport.update({
    id: '/tomatoe',
    path: '/tomatoe',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutVegetablesPepperRoute =
  mainLayoutVegetablesPepperRouteImport.update({
    id: '/pepper',
    path: '/pepper',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutVegetablesCucumberRoute =
  mainLayoutVegetablesCucumberRouteImport.update({
    id: '/cucumber',
    path: '/cucumber',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutvaluesVisionMissionRoute =
  mainLayoutvaluesVisionMissionRouteImport.update({
    id: '/(values)/vision-mission',
    path: '/vision-mission',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutvaluesSustainabillityRoute =
  mainLayoutvaluesSustainabillityRouteImport.update({
    id: '/(values)/sustainabillity',
    path: '/sustainabillity',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutvaluesQualityPolicyRoute =
  mainLayoutvaluesQualityPolicyRouteImport.update({
    id: '/(values)/quality-policy',
    path: '/quality-policy',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vegetables': typeof mainLayoutVegetablesRouteRouteWithChildren
  '/about-us': typeof mainLayoutAboutUsRoute
  '/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/vision-mission': typeof mainLayoutvaluesVisionMissionRoute
  '/vegetables/cucumber': typeof mainLayoutVegetablesCucumberRoute
  '/vegetables/pepper': typeof mainLayoutVegetablesPepperRoute
  '/vegetables/tomatoe': typeof mainLayoutVegetablesTomatoeRoute
  '/fruits': typeof mainLayoutFruitsIndexRoute
  '/vegetables/': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof mainLayoutAboutUsRoute
  '/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/vision-mission': typeof mainLayoutvaluesVisionMissionRoute
  '/vegetables/cucumber': typeof mainLayoutVegetablesCucumberRoute
  '/vegetables/pepper': typeof mainLayoutVegetablesPepperRoute
  '/vegetables/tomatoe': typeof mainLayoutVegetablesTomatoeRoute
  '/fruits': typeof mainLayoutFruitsIndexRoute
  '/vegetables': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main-layout)': typeof mainLayoutRouteRouteWithChildren
  '/(main-layout)/vegetables': typeof mainLayoutVegetablesRouteRouteWithChildren
  '/(main-layout)/about-us': typeof mainLayoutAboutUsRoute
  '/(main-layout)/(values)/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/(main-layout)/(values)/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/(main-layout)/(values)/vision-mission': typeof mainLayoutvaluesVisionMissionRoute
  '/(main-layout)/vegetables/cucumber': typeof mainLayoutVegetablesCucumberRoute
  '/(main-layout)/vegetables/pepper': typeof mainLayoutVegetablesPepperRoute
  '/(main-layout)/vegetables/tomatoe': typeof mainLayoutVegetablesTomatoeRoute
  '/(main-layout)/fruits/': typeof mainLayoutFruitsIndexRoute
  '/(main-layout)/vegetables/': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vegetables'
    | '/about-us'
    | '/quality-policy'
    | '/sustainabillity'
    | '/vision-mission'
    | '/vegetables/cucumber'
    | '/vegetables/pepper'
    | '/vegetables/tomatoe'
    | '/fruits'
    | '/vegetables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/quality-policy'
    | '/sustainabillity'
    | '/vision-mission'
    | '/vegetables/cucumber'
    | '/vegetables/pepper'
    | '/vegetables/tomatoe'
    | '/fruits'
    | '/vegetables'
  id:
    | '__root__'
    | '/'
    | '/(main-layout)'
    | '/(main-layout)/vegetables'
    | '/(main-layout)/about-us'
    | '/(main-layout)/(values)/quality-policy'
    | '/(main-layout)/(values)/sustainabillity'
    | '/(main-layout)/(values)/vision-mission'
    | '/(main-layout)/vegetables/cucumber'
    | '/(main-layout)/vegetables/pepper'
    | '/(main-layout)/vegetables/tomatoe'
    | '/(main-layout)/fruits/'
    | '/(main-layout)/vegetables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainLayoutRouteRoute: typeof mainLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main-layout)': {
      id: '/(main-layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main-layout)/about-us': {
      id: '/(main-layout)/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof mainLayoutAboutUsRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/vegetables': {
      id: '/(main-layout)/vegetables'
      path: '/vegetables'
      fullPath: '/vegetables'
      preLoaderRoute: typeof mainLayoutVegetablesRouteRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/vegetables/': {
      id: '/(main-layout)/vegetables/'
      path: '/'
      fullPath: '/vegetables/'
      preLoaderRoute: typeof mainLayoutVegetablesIndexRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/fruits/': {
      id: '/(main-layout)/fruits/'
      path: '/fruits'
      fullPath: '/fruits'
      preLoaderRoute: typeof mainLayoutFruitsIndexRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/vegetables/tomatoe': {
      id: '/(main-layout)/vegetables/tomatoe'
      path: '/tomatoe'
      fullPath: '/vegetables/tomatoe'
      preLoaderRoute: typeof mainLayoutVegetablesTomatoeRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/vegetables/pepper': {
      id: '/(main-layout)/vegetables/pepper'
      path: '/pepper'
      fullPath: '/vegetables/pepper'
      preLoaderRoute: typeof mainLayoutVegetablesPepperRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/vegetables/cucumber': {
      id: '/(main-layout)/vegetables/cucumber'
      path: '/cucumber'
      fullPath: '/vegetables/cucumber'
      preLoaderRoute: typeof mainLayoutVegetablesCucumberRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/(values)/vision-mission': {
      id: '/(main-layout)/(values)/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof mainLayoutvaluesVisionMissionRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/(values)/sustainabillity': {
      id: '/(main-layout)/(values)/sustainabillity'
      path: '/sustainabillity'
      fullPath: '/sustainabillity'
      preLoaderRoute: typeof mainLayoutvaluesSustainabillityRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/(values)/quality-policy': {
      id: '/(main-layout)/(values)/quality-policy'
      path: '/quality-policy'
      fullPath: '/quality-policy'
      preLoaderRoute: typeof mainLayoutvaluesQualityPolicyRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
  }
}

interface mainLayoutVegetablesRouteRouteChildren {
  mainLayoutVegetablesCucumberRoute: typeof mainLayoutVegetablesCucumberRoute
  mainLayoutVegetablesPepperRoute: typeof mainLayoutVegetablesPepperRoute
  mainLayoutVegetablesTomatoeRoute: typeof mainLayoutVegetablesTomatoeRoute
  mainLayoutVegetablesIndexRoute: typeof mainLayoutVegetablesIndexRoute
}

const mainLayoutVegetablesRouteRouteChildren: mainLayoutVegetablesRouteRouteChildren =
  {
    mainLayoutVegetablesCucumberRoute: mainLayoutVegetablesCucumberRoute,
    mainLayoutVegetablesPepperRoute: mainLayoutVegetablesPepperRoute,
    mainLayoutVegetablesTomatoeRoute: mainLayoutVegetablesTomatoeRoute,
    mainLayoutVegetablesIndexRoute: mainLayoutVegetablesIndexRoute,
  }

const mainLayoutVegetablesRouteRouteWithChildren =
  mainLayoutVegetablesRouteRoute._addFileChildren(
    mainLayoutVegetablesRouteRouteChildren,
  )

interface mainLayoutRouteRouteChildren {
  mainLayoutVegetablesRouteRoute: typeof mainLayoutVegetablesRouteRouteWithChildren
  mainLayoutAboutUsRoute: typeof mainLayoutAboutUsRoute
  mainLayoutvaluesQualityPolicyRoute: typeof mainLayoutvaluesQualityPolicyRoute
  mainLayoutvaluesSustainabillityRoute: typeof mainLayoutvaluesSustainabillityRoute
  mainLayoutvaluesVisionMissionRoute: typeof mainLayoutvaluesVisionMissionRoute
  mainLayoutFruitsIndexRoute: typeof mainLayoutFruitsIndexRoute
}

const mainLayoutRouteRouteChildren: mainLayoutRouteRouteChildren = {
  mainLayoutVegetablesRouteRoute: mainLayoutVegetablesRouteRouteWithChildren,
  mainLayoutAboutUsRoute: mainLayoutAboutUsRoute,
  mainLayoutvaluesQualityPolicyRoute: mainLayoutvaluesQualityPolicyRoute,
  mainLayoutvaluesSustainabillityRoute: mainLayoutvaluesSustainabillityRoute,
  mainLayoutvaluesVisionMissionRoute: mainLayoutvaluesVisionMissionRoute,
  mainLayoutFruitsIndexRoute: mainLayoutFruitsIndexRoute,
}

const mainLayoutRouteRouteWithChildren = mainLayoutRouteRoute._addFileChildren(
  mainLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainLayoutRouteRoute: mainLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
