/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainLayoutRouteRouteImport } from './routes/(main-layout)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainLayoutAboutUsRouteImport } from './routes/(main-layout)/about-us'
import { Route as mainLayoutVegetablesIndexRouteImport } from './routes/(main-layout)/vegetables/index'
import { Route as mainLayoutFruitsIndexRouteImport } from './routes/(main-layout)/fruits/index'
import { Route as mainLayoutvaluesSustainabillityRouteImport } from './routes/(main-layout)/(values)/sustainabillity'
import { Route as mainLayoutvaluesQualityPolicyRouteImport } from './routes/(main-layout)/(values)/quality-policy'

const mainLayoutRouteRoute = mainLayoutRouteRouteImport.update({
  id: '/(main-layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutAboutUsRoute = mainLayoutAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => mainLayoutRouteRoute,
} as any)
const mainLayoutVegetablesIndexRoute =
  mainLayoutVegetablesIndexRouteImport.update({
    id: '/vegetables/',
    path: '/vegetables/',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutFruitsIndexRoute = mainLayoutFruitsIndexRouteImport.update({
  id: '/fruits/',
  path: '/fruits/',
  getParentRoute: () => mainLayoutRouteRoute,
} as any)
const mainLayoutvaluesSustainabillityRoute =
  mainLayoutvaluesSustainabillityRouteImport.update({
    id: '/(values)/sustainabillity',
    path: '/sustainabillity',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutvaluesQualityPolicyRoute =
  mainLayoutvaluesQualityPolicyRouteImport.update({
    id: '/(values)/quality-policy',
    path: '/quality-policy',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof mainLayoutAboutUsRoute
  '/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/fruits': typeof mainLayoutFruitsIndexRoute
  '/vegetables': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof mainLayoutAboutUsRoute
  '/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/fruits': typeof mainLayoutFruitsIndexRoute
  '/vegetables': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main-layout)': typeof mainLayoutRouteRouteWithChildren
  '/(main-layout)/about-us': typeof mainLayoutAboutUsRoute
  '/(main-layout)/(values)/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/(main-layout)/(values)/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/(main-layout)/fruits/': typeof mainLayoutFruitsIndexRoute
  '/(main-layout)/vegetables/': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/quality-policy'
    | '/sustainabillity'
    | '/fruits'
    | '/vegetables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/quality-policy'
    | '/sustainabillity'
    | '/fruits'
    | '/vegetables'
  id:
    | '__root__'
    | '/'
    | '/(main-layout)'
    | '/(main-layout)/about-us'
    | '/(main-layout)/(values)/quality-policy'
    | '/(main-layout)/(values)/sustainabillity'
    | '/(main-layout)/fruits/'
    | '/(main-layout)/vegetables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainLayoutRouteRoute: typeof mainLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main-layout)': {
      id: '/(main-layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main-layout)/about-us': {
      id: '/(main-layout)/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof mainLayoutAboutUsRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/vegetables/': {
      id: '/(main-layout)/vegetables/'
      path: '/vegetables'
      fullPath: '/vegetables'
      preLoaderRoute: typeof mainLayoutVegetablesIndexRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/fruits/': {
      id: '/(main-layout)/fruits/'
      path: '/fruits'
      fullPath: '/fruits'
      preLoaderRoute: typeof mainLayoutFruitsIndexRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/(values)/sustainabillity': {
      id: '/(main-layout)/(values)/sustainabillity'
      path: '/sustainabillity'
      fullPath: '/sustainabillity'
      preLoaderRoute: typeof mainLayoutvaluesSustainabillityRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/(values)/quality-policy': {
      id: '/(main-layout)/(values)/quality-policy'
      path: '/quality-policy'
      fullPath: '/quality-policy'
      preLoaderRoute: typeof mainLayoutvaluesQualityPolicyRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
  }
}

interface mainLayoutRouteRouteChildren {
  mainLayoutAboutUsRoute: typeof mainLayoutAboutUsRoute
  mainLayoutvaluesQualityPolicyRoute: typeof mainLayoutvaluesQualityPolicyRoute
  mainLayoutvaluesSustainabillityRoute: typeof mainLayoutvaluesSustainabillityRoute
  mainLayoutFruitsIndexRoute: typeof mainLayoutFruitsIndexRoute
  mainLayoutVegetablesIndexRoute: typeof mainLayoutVegetablesIndexRoute
}

const mainLayoutRouteRouteChildren: mainLayoutRouteRouteChildren = {
  mainLayoutAboutUsRoute: mainLayoutAboutUsRoute,
  mainLayoutvaluesQualityPolicyRoute: mainLayoutvaluesQualityPolicyRoute,
  mainLayoutvaluesSustainabillityRoute: mainLayoutvaluesSustainabillityRoute,
  mainLayoutFruitsIndexRoute: mainLayoutFruitsIndexRoute,
  mainLayoutVegetablesIndexRoute: mainLayoutVegetablesIndexRoute,
}

const mainLayoutRouteRouteWithChildren = mainLayoutRouteRoute._addFileChildren(
  mainLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainLayoutRouteRoute: mainLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
