/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as mainLayoutRouteRouteImport } from './routes/(main-layout)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainLayoutAboutUsRouteImport } from './routes/(main-layout)/about-us'
import { Route as mainLayoutVegetablesRouteRouteImport } from './routes/(main-layout)/vegetables/route'
import { Route as mainLayoutFruitsRouteRouteImport } from './routes/(main-layout)/fruits/route'
import { Route as mainLayoutVegetablesIndexRouteImport } from './routes/(main-layout)/vegetables/index'
import { Route as mainLayoutFruitsIndexRouteImport } from './routes/(main-layout)/fruits/index'
import { Route as mainLayoutVegetablesZucchiniRouteImport } from './routes/(main-layout)/vegetables/zucchini'
import { Route as mainLayoutVegetablesTomatoeRouteImport } from './routes/(main-layout)/vegetables/tomatoe'
import { Route as mainLayoutVegetablesSquashRouteImport } from './routes/(main-layout)/vegetables/squash'
import { Route as mainLayoutVegetablesPepperRouteImport } from './routes/(main-layout)/vegetables/pepper'
import { Route as mainLayoutVegetablesCucumberRouteImport } from './routes/(main-layout)/vegetables/cucumber'
import { Route as mainLayoutFruitsPomegranateRouteImport } from './routes/(main-layout)/fruits/pomegranate'
import { Route as mainLayoutFruitsMandarinRouteImport } from './routes/(main-layout)/fruits/mandarin'
import { Route as mainLayoutFruitsLemonRouteImport } from './routes/(main-layout)/fruits/lemon'
import { Route as mainLayoutvaluesVisionMissionRouteImport } from './routes/(main-layout)/(values)/vision-mission'
import { Route as mainLayoutvaluesSustainabillityRouteImport } from './routes/(main-layout)/(values)/sustainabillity'
import { Route as mainLayoutvaluesQualityPolicyRouteImport } from './routes/(main-layout)/(values)/quality-policy'

const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutRouteRoute = mainLayoutRouteRouteImport.update({
  id: '/(main-layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutAboutUsRoute = mainLayoutAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => mainLayoutRouteRoute,
} as any)
const mainLayoutVegetablesRouteRoute =
  mainLayoutVegetablesRouteRouteImport.update({
    id: '/vegetables',
    path: '/vegetables',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutFruitsRouteRoute = mainLayoutFruitsRouteRouteImport.update({
  id: '/fruits',
  path: '/fruits',
  getParentRoute: () => mainLayoutRouteRoute,
} as any)
const mainLayoutVegetablesIndexRoute =
  mainLayoutVegetablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutFruitsIndexRoute = mainLayoutFruitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainLayoutFruitsRouteRoute,
} as any)
const mainLayoutVegetablesZucchiniRoute =
  mainLayoutVegetablesZucchiniRouteImport.update({
    id: '/zucchini',
    path: '/zucchini',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutVegetablesTomatoeRoute =
  mainLayoutVegetablesTomatoeRouteImport.update({
    id: '/tomatoe',
    path: '/tomatoe',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutVegetablesSquashRoute =
  mainLayoutVegetablesSquashRouteImport.update({
    id: '/squash',
    path: '/squash',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutVegetablesPepperRoute =
  mainLayoutVegetablesPepperRouteImport.update({
    id: '/pepper',
    path: '/pepper',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutVegetablesCucumberRoute =
  mainLayoutVegetablesCucumberRouteImport.update({
    id: '/cucumber',
    path: '/cucumber',
    getParentRoute: () => mainLayoutVegetablesRouteRoute,
  } as any)
const mainLayoutFruitsPomegranateRoute =
  mainLayoutFruitsPomegranateRouteImport.update({
    id: '/pomegranate',
    path: '/pomegranate',
    getParentRoute: () => mainLayoutFruitsRouteRoute,
  } as any)
const mainLayoutFruitsMandarinRoute =
  mainLayoutFruitsMandarinRouteImport.update({
    id: '/mandarin',
    path: '/mandarin',
    getParentRoute: () => mainLayoutFruitsRouteRoute,
  } as any)
const mainLayoutFruitsLemonRoute = mainLayoutFruitsLemonRouteImport.update({
  id: '/lemon',
  path: '/lemon',
  getParentRoute: () => mainLayoutFruitsRouteRoute,
} as any)
const mainLayoutvaluesVisionMissionRoute =
  mainLayoutvaluesVisionMissionRouteImport.update({
    id: '/(values)/vision-mission',
    path: '/vision-mission',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutvaluesSustainabillityRoute =
  mainLayoutvaluesSustainabillityRouteImport.update({
    id: '/(values)/sustainabillity',
    path: '/sustainabillity',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)
const mainLayoutvaluesQualityPolicyRoute =
  mainLayoutvaluesQualityPolicyRouteImport.update({
    id: '/(values)/quality-policy',
    path: '/quality-policy',
    getParentRoute: () => mainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/fruits': typeof mainLayoutFruitsRouteRouteWithChildren
  '/vegetables': typeof mainLayoutVegetablesRouteRouteWithChildren
  '/about-us': typeof mainLayoutAboutUsRoute
  '/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/vision-mission': typeof mainLayoutvaluesVisionMissionRoute
  '/fruits/lemon': typeof mainLayoutFruitsLemonRoute
  '/fruits/mandarin': typeof mainLayoutFruitsMandarinRoute
  '/fruits/pomegranate': typeof mainLayoutFruitsPomegranateRoute
  '/vegetables/cucumber': typeof mainLayoutVegetablesCucumberRoute
  '/vegetables/pepper': typeof mainLayoutVegetablesPepperRoute
  '/vegetables/squash': typeof mainLayoutVegetablesSquashRoute
  '/vegetables/tomatoe': typeof mainLayoutVegetablesTomatoeRoute
  '/vegetables/zucchini': typeof mainLayoutVegetablesZucchiniRoute
  '/fruits/': typeof mainLayoutFruitsIndexRoute
  '/vegetables/': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/about-us': typeof mainLayoutAboutUsRoute
  '/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/vision-mission': typeof mainLayoutvaluesVisionMissionRoute
  '/fruits/lemon': typeof mainLayoutFruitsLemonRoute
  '/fruits/mandarin': typeof mainLayoutFruitsMandarinRoute
  '/fruits/pomegranate': typeof mainLayoutFruitsPomegranateRoute
  '/vegetables/cucumber': typeof mainLayoutVegetablesCucumberRoute
  '/vegetables/pepper': typeof mainLayoutVegetablesPepperRoute
  '/vegetables/squash': typeof mainLayoutVegetablesSquashRoute
  '/vegetables/tomatoe': typeof mainLayoutVegetablesTomatoeRoute
  '/vegetables/zucchini': typeof mainLayoutVegetablesZucchiniRoute
  '/fruits': typeof mainLayoutFruitsIndexRoute
  '/vegetables': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main-layout)': typeof mainLayoutRouteRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/(main-layout)/fruits': typeof mainLayoutFruitsRouteRouteWithChildren
  '/(main-layout)/vegetables': typeof mainLayoutVegetablesRouteRouteWithChildren
  '/(main-layout)/about-us': typeof mainLayoutAboutUsRoute
  '/(main-layout)/(values)/quality-policy': typeof mainLayoutvaluesQualityPolicyRoute
  '/(main-layout)/(values)/sustainabillity': typeof mainLayoutvaluesSustainabillityRoute
  '/(main-layout)/(values)/vision-mission': typeof mainLayoutvaluesVisionMissionRoute
  '/(main-layout)/fruits/lemon': typeof mainLayoutFruitsLemonRoute
  '/(main-layout)/fruits/mandarin': typeof mainLayoutFruitsMandarinRoute
  '/(main-layout)/fruits/pomegranate': typeof mainLayoutFruitsPomegranateRoute
  '/(main-layout)/vegetables/cucumber': typeof mainLayoutVegetablesCucumberRoute
  '/(main-layout)/vegetables/pepper': typeof mainLayoutVegetablesPepperRoute
  '/(main-layout)/vegetables/squash': typeof mainLayoutVegetablesSquashRoute
  '/(main-layout)/vegetables/tomatoe': typeof mainLayoutVegetablesTomatoeRoute
  '/(main-layout)/vegetables/zucchini': typeof mainLayoutVegetablesZucchiniRoute
  '/(main-layout)/fruits/': typeof mainLayoutFruitsIndexRoute
  '/(main-layout)/vegetables/': typeof mainLayoutVegetablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/fruits'
    | '/vegetables'
    | '/about-us'
    | '/quality-policy'
    | '/sustainabillity'
    | '/vision-mission'
    | '/fruits/lemon'
    | '/fruits/mandarin'
    | '/fruits/pomegranate'
    | '/vegetables/cucumber'
    | '/vegetables/pepper'
    | '/vegetables/squash'
    | '/vegetables/tomatoe'
    | '/vegetables/zucchini'
    | '/fruits/'
    | '/vegetables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/about-us'
    | '/quality-policy'
    | '/sustainabillity'
    | '/vision-mission'
    | '/fruits/lemon'
    | '/fruits/mandarin'
    | '/fruits/pomegranate'
    | '/vegetables/cucumber'
    | '/vegetables/pepper'
    | '/vegetables/squash'
    | '/vegetables/tomatoe'
    | '/vegetables/zucchini'
    | '/fruits'
    | '/vegetables'
  id:
    | '__root__'
    | '/'
    | '/(main-layout)'
    | '/contacts'
    | '/(main-layout)/fruits'
    | '/(main-layout)/vegetables'
    | '/(main-layout)/about-us'
    | '/(main-layout)/(values)/quality-policy'
    | '/(main-layout)/(values)/sustainabillity'
    | '/(main-layout)/(values)/vision-mission'
    | '/(main-layout)/fruits/lemon'
    | '/(main-layout)/fruits/mandarin'
    | '/(main-layout)/fruits/pomegranate'
    | '/(main-layout)/vegetables/cucumber'
    | '/(main-layout)/vegetables/pepper'
    | '/(main-layout)/vegetables/squash'
    | '/(main-layout)/vegetables/tomatoe'
    | '/(main-layout)/vegetables/zucchini'
    | '/(main-layout)/fruits/'
    | '/(main-layout)/vegetables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainLayoutRouteRoute: typeof mainLayoutRouteRouteWithChildren
  ContactsRoute: typeof ContactsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main-layout)': {
      id: '/(main-layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main-layout)/about-us': {
      id: '/(main-layout)/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof mainLayoutAboutUsRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/vegetables': {
      id: '/(main-layout)/vegetables'
      path: '/vegetables'
      fullPath: '/vegetables'
      preLoaderRoute: typeof mainLayoutVegetablesRouteRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/fruits': {
      id: '/(main-layout)/fruits'
      path: '/fruits'
      fullPath: '/fruits'
      preLoaderRoute: typeof mainLayoutFruitsRouteRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/vegetables/': {
      id: '/(main-layout)/vegetables/'
      path: '/'
      fullPath: '/vegetables/'
      preLoaderRoute: typeof mainLayoutVegetablesIndexRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/fruits/': {
      id: '/(main-layout)/fruits/'
      path: '/'
      fullPath: '/fruits/'
      preLoaderRoute: typeof mainLayoutFruitsIndexRouteImport
      parentRoute: typeof mainLayoutFruitsRouteRoute
    }
    '/(main-layout)/vegetables/zucchini': {
      id: '/(main-layout)/vegetables/zucchini'
      path: '/zucchini'
      fullPath: '/vegetables/zucchini'
      preLoaderRoute: typeof mainLayoutVegetablesZucchiniRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/vegetables/tomatoe': {
      id: '/(main-layout)/vegetables/tomatoe'
      path: '/tomatoe'
      fullPath: '/vegetables/tomatoe'
      preLoaderRoute: typeof mainLayoutVegetablesTomatoeRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/vegetables/squash': {
      id: '/(main-layout)/vegetables/squash'
      path: '/squash'
      fullPath: '/vegetables/squash'
      preLoaderRoute: typeof mainLayoutVegetablesSquashRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/vegetables/pepper': {
      id: '/(main-layout)/vegetables/pepper'
      path: '/pepper'
      fullPath: '/vegetables/pepper'
      preLoaderRoute: typeof mainLayoutVegetablesPepperRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/vegetables/cucumber': {
      id: '/(main-layout)/vegetables/cucumber'
      path: '/cucumber'
      fullPath: '/vegetables/cucumber'
      preLoaderRoute: typeof mainLayoutVegetablesCucumberRouteImport
      parentRoute: typeof mainLayoutVegetablesRouteRoute
    }
    '/(main-layout)/fruits/pomegranate': {
      id: '/(main-layout)/fruits/pomegranate'
      path: '/pomegranate'
      fullPath: '/fruits/pomegranate'
      preLoaderRoute: typeof mainLayoutFruitsPomegranateRouteImport
      parentRoute: typeof mainLayoutFruitsRouteRoute
    }
    '/(main-layout)/fruits/mandarin': {
      id: '/(main-layout)/fruits/mandarin'
      path: '/mandarin'
      fullPath: '/fruits/mandarin'
      preLoaderRoute: typeof mainLayoutFruitsMandarinRouteImport
      parentRoute: typeof mainLayoutFruitsRouteRoute
    }
    '/(main-layout)/fruits/lemon': {
      id: '/(main-layout)/fruits/lemon'
      path: '/lemon'
      fullPath: '/fruits/lemon'
      preLoaderRoute: typeof mainLayoutFruitsLemonRouteImport
      parentRoute: typeof mainLayoutFruitsRouteRoute
    }
    '/(main-layout)/(values)/vision-mission': {
      id: '/(main-layout)/(values)/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof mainLayoutvaluesVisionMissionRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/(values)/sustainabillity': {
      id: '/(main-layout)/(values)/sustainabillity'
      path: '/sustainabillity'
      fullPath: '/sustainabillity'
      preLoaderRoute: typeof mainLayoutvaluesSustainabillityRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
    '/(main-layout)/(values)/quality-policy': {
      id: '/(main-layout)/(values)/quality-policy'
      path: '/quality-policy'
      fullPath: '/quality-policy'
      preLoaderRoute: typeof mainLayoutvaluesQualityPolicyRouteImport
      parentRoute: typeof mainLayoutRouteRoute
    }
  }
}

interface mainLayoutFruitsRouteRouteChildren {
  mainLayoutFruitsLemonRoute: typeof mainLayoutFruitsLemonRoute
  mainLayoutFruitsMandarinRoute: typeof mainLayoutFruitsMandarinRoute
  mainLayoutFruitsPomegranateRoute: typeof mainLayoutFruitsPomegranateRoute
  mainLayoutFruitsIndexRoute: typeof mainLayoutFruitsIndexRoute
}

const mainLayoutFruitsRouteRouteChildren: mainLayoutFruitsRouteRouteChildren = {
  mainLayoutFruitsLemonRoute: mainLayoutFruitsLemonRoute,
  mainLayoutFruitsMandarinRoute: mainLayoutFruitsMandarinRoute,
  mainLayoutFruitsPomegranateRoute: mainLayoutFruitsPomegranateRoute,
  mainLayoutFruitsIndexRoute: mainLayoutFruitsIndexRoute,
}

const mainLayoutFruitsRouteRouteWithChildren =
  mainLayoutFruitsRouteRoute._addFileChildren(
    mainLayoutFruitsRouteRouteChildren,
  )

interface mainLayoutVegetablesRouteRouteChildren {
  mainLayoutVegetablesCucumberRoute: typeof mainLayoutVegetablesCucumberRoute
  mainLayoutVegetablesPepperRoute: typeof mainLayoutVegetablesPepperRoute
  mainLayoutVegetablesSquashRoute: typeof mainLayoutVegetablesSquashRoute
  mainLayoutVegetablesTomatoeRoute: typeof mainLayoutVegetablesTomatoeRoute
  mainLayoutVegetablesZucchiniRoute: typeof mainLayoutVegetablesZucchiniRoute
  mainLayoutVegetablesIndexRoute: typeof mainLayoutVegetablesIndexRoute
}

const mainLayoutVegetablesRouteRouteChildren: mainLayoutVegetablesRouteRouteChildren =
  {
    mainLayoutVegetablesCucumberRoute: mainLayoutVegetablesCucumberRoute,
    mainLayoutVegetablesPepperRoute: mainLayoutVegetablesPepperRoute,
    mainLayoutVegetablesSquashRoute: mainLayoutVegetablesSquashRoute,
    mainLayoutVegetablesTomatoeRoute: mainLayoutVegetablesTomatoeRoute,
    mainLayoutVegetablesZucchiniRoute: mainLayoutVegetablesZucchiniRoute,
    mainLayoutVegetablesIndexRoute: mainLayoutVegetablesIndexRoute,
  }

const mainLayoutVegetablesRouteRouteWithChildren =
  mainLayoutVegetablesRouteRoute._addFileChildren(
    mainLayoutVegetablesRouteRouteChildren,
  )

interface mainLayoutRouteRouteChildren {
  mainLayoutFruitsRouteRoute: typeof mainLayoutFruitsRouteRouteWithChildren
  mainLayoutVegetablesRouteRoute: typeof mainLayoutVegetablesRouteRouteWithChildren
  mainLayoutAboutUsRoute: typeof mainLayoutAboutUsRoute
  mainLayoutvaluesQualityPolicyRoute: typeof mainLayoutvaluesQualityPolicyRoute
  mainLayoutvaluesSustainabillityRoute: typeof mainLayoutvaluesSustainabillityRoute
  mainLayoutvaluesVisionMissionRoute: typeof mainLayoutvaluesVisionMissionRoute
}

const mainLayoutRouteRouteChildren: mainLayoutRouteRouteChildren = {
  mainLayoutFruitsRouteRoute: mainLayoutFruitsRouteRouteWithChildren,
  mainLayoutVegetablesRouteRoute: mainLayoutVegetablesRouteRouteWithChildren,
  mainLayoutAboutUsRoute: mainLayoutAboutUsRoute,
  mainLayoutvaluesQualityPolicyRoute: mainLayoutvaluesQualityPolicyRoute,
  mainLayoutvaluesSustainabillityRoute: mainLayoutvaluesSustainabillityRoute,
  mainLayoutvaluesVisionMissionRoute: mainLayoutvaluesVisionMissionRoute,
}

const mainLayoutRouteRouteWithChildren = mainLayoutRouteRoute._addFileChildren(
  mainLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainLayoutRouteRoute: mainLayoutRouteRouteWithChildren,
  ContactsRoute: ContactsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
